// Generated from docs/island/island-tokens.json by tools/gen-island.mjs. Do not edit; change the tokens.
package ai.ash.screen.island

/** The designer's island tokens, in dp, ms and ARGB. */
internal object IslandTokens {
    const val SIZE_COMPACT_W = 236f
    const val SIZE_COMPACT_H = 40f
    const val SIZE_COMPACT_RADIUS = 20f
    const val SIZE_COMPACT_HUG_CAMERA_W = 236f
    const val SIZE_COMPACT_HUG_CAMERA_H = 34f
    const val SIZE_COMPACT_HUG_CAMERA_RADIUS = 17f
    const val SIZE_CARD_W = 362f
    const val SIZE_CARD_RADIUS = 30f
    val SIZE_CARD_PADDING = floatArrayOf(16f, 16f, 10f, 16f)
    const val SIZE_CARD_GAP = 14f
    const val SIZE_EDGE_W = 52f
    const val SIZE_EDGE_H = 52f
    const val SIZE_EDGE_RADIUS = 26f
    const val SIZE_PILL_PAD_Y = 4f
    const val SIZE_PILL_GAP_PAD = 2f
    const val SIZE_PILL_RESIDENT_SEGMENT = 28f
    const val SIZE_PILL_RUNNING_SEGMENT_MAX = 80f
    const val SIZE_PILL_NO_CUTOUT_H = 28f
    const val SIZE_PILL_MIN_H = 24f
    const val SIZE_PILL_EDGE_MARGIN = 4f
    const val SIZE_PILL_PAD_OUTER = 6f
    const val SIZE_PILL_PAD_INNER = 6f
    const val SIZE_PILL_GAP = 6f
    const val SIZE_PILL_DOT = 7f
    const val SIZE_TOP_BELOW_STATUS_BAR = 8f
    const val SIZE_TOP_HUG_CAMERA = 5f
    const val SIZE_MIN_TOUCH = 44f
    const val SIZE_WINDOW_INSET_TOP = 8f
    const val SIZE_WINDOW_INSET_SIDE = 16f
    const val SIZE_WINDOW_INSET_BOTTOM = 24f
    val SHADOW_LAYERS = arrayOf(floatArrayOf(0f, 8f, 16f), floatArrayOf(0f, 1f, 3f))
    val SHADOW_COLORS = intArrayOf(0x4D000000.toInt(), 0x38000000.toInt())
    const val COLOR_ISLAND = 0xFF101011.toInt()
    const val COLOR_PILL = 0xFF000000.toInt()
    const val COLOR_ISLAND_STROKE = 0x0FFFFFFF.toInt()
    const val COLOR_SURFACE = 0xFF1A1A1C.toInt()
    const val COLOR_INPUT = 0xFF1E1E21.toInt()
    const val COLOR_ICON_BUTTON = 0xFF1F1F22.toInt()
    const val COLOR_NEUTRAL_BUTTON = 0xFF26262A.toInt()
    const val COLOR_DIVIDER = 0xFF222225.toInt()
    const val COLOR_TEXT = 0xFFF2F2F4.toInt()
    const val COLOR_BODY = 0xFFE6E6E9.toInt()
    const val COLOR_TEXT_SECONDARY = 0xFFA1A1A7.toInt()
    const val COLOR_PLACEHOLDER = 0xFF7D7D83.toInt()
    const val COLOR_RUNNING = 0xFF5AD8DB.toInt()
    const val COLOR_NEEDS_YOU = 0xFFF5A623.toInt()
    const val COLOR_NEEDS_YOU_TEXT = 0xFFFFD08A.toInt()
    const val COLOR_DONE = 0xFF2BB673.toInt()
    const val COLOR_DONE_TEXT = 0xFF6FD9A4.toInt()
    const val COLOR_STOP = 0xFFFF6B6B.toInt()
    const val COLOR_STOP_TEXT = 0xFFFF8A8A.toInt()
    const val COLOR_OFFLINE = 0xFF8D8D93.toInt()
    const val COLOR_PRIMARY = 0xFF3B74FF.toInt()
    const val TYPE_COMPACT_LABEL_SIZE = 12f
    const val TYPE_COMPACT_LABEL_WEIGHT = 500f
    const val TYPE_COMPACT_TIME_SIZE = 11.5f
    const val TYPE_COMPACT_TIME_WEIGHT = 400f
    const val TYPE_CARD_TITLE_SIZE = 16f
    const val TYPE_CARD_TITLE_WEIGHT = 650f
    const val TYPE_CARD_META_SIZE = 12f
    const val TYPE_CARD_META_WEIGHT = 400f
    const val TYPE_BODY_SIZE = 14.5f
    const val TYPE_BODY_LINE_HEIGHT = 1.6f
    const val TYPE_BODY_COLLAPSED_LINES = 4f
    const val TYPE_BUTTON_SIZE = 14f
    const val TYPE_BUTTON_WEIGHT = 600f
    const val TYPE_PRIMARY_BUTTON_SIZE = 15f
    const val TYPE_PRIMARY_BUTTON_WEIGHT = 650f
    const val TYPE_PRIMARY_BUTTON_HEIGHT = 46f
    const val TYPE_FOOTER_LINK_SIZE = 13.5f
    const val MOTION_MORPH_MS = 500L
    val MOTION_MORPH_EASING = floatArrayOf(0.32f, 0.72f, 0f, 1f)
    const val MOTION_CONTENT_IN_MS = 340L
    const val MOTION_CONTENT_IN_DELAY_MS = 100L
    const val MOTION_CONTENT_IN_FROM_OPACITY = 0f
    const val MOTION_CONTENT_IN_FROM_TRANSLATE_Y = -4f
    const val MOTION_CONTENT_IN_FROM_SCALE = 0.98f
    const val MOTION_PULSE_MS = 1400L
    const val MOTION_SPIN_MS = 1000L
    const val MOTION_RESPECT_REDUCED_MOTION = true
    const val AVATAR_COMPACT = 28f
    const val AVATAR_COMPACT_HUG_CAMERA = 24f
    const val AVATAR_CARD_SIZE = 40f
    const val AVATAR_CARD_RADIUS = 14f
    const val AVATAR_EDGE = 42f
    const val AVATAR_PILL = 16f
    val AVATAR_FACE_BY_KIND = mapOf("listening" to "listening", "thinking" to "thinking", "working" to "focused", "ask" to "listening", "approval" to "focused", "in_app" to "listening", "result" to "success", "incomplete" to "thinking", "stopped" to "default", "stale" to "default")
}
