#!/usr/bin/env node
// ash's own apps (packages/apps/<id>) bundled into one module the core carries: app.json, a single-file server, the icon.
// The core puts each into <container>/root/apps/<id>/ when it is missing or older. Edit the app, then `npm run gen:apps`.
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const appsDir = join(root, "packages/apps");
const out = [];
for (const id of readdirSync(appsDir).sort()) {
  const dir = join(appsDir, id);
  if (!existsSync(join(dir, "app.json"))) continue;
  const manifest = JSON.parse(readFileSync(join(dir, "app.json"), "utf8"));
  const bundled = await build({ entryPoints: [join(dir, "src/server.mjs")], bundle: true, write: false, platform: "node", format: "esm", target: "node20",
    minify: true, legalComments: "none", loader: { ".html": "text" }, logLevel: "silent",
    banner: { js: "import{createRequire as __cr}from'node:module';const require=__cr(import.meta.url);" } });
  const files = { "app.json": `${JSON.stringify(manifest, null, 2)}\n`, "server.mjs": bundled.outputFiles[0].text };
  if (manifest.icon) files[manifest.icon] = readFileSync(join(dir, manifest.icon), "utf8");
  out.push({ id, version: manifest.version, files });
}
writeFileSync(join(root, "packages/core/src/apps/builtin.generated.ts"),
  `// GENERATED by tools/gen-apps.mjs from packages/apps/ — edit those files, then \`npm run gen:apps\`.\n\n` +
  `export const BUILTIN_APPS: { id: string; version: string; files: Record<string, string> }[] = ${JSON.stringify(out)};\n`);
