#!/usr/bin/env node
// packages/core/ui/* → packages/core/src/ui.ts (one bundle file ships the UI; no assets to copy).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ui = join(dirname(fileURLToPath(import.meta.url)), "../packages/core/ui");
const read = (f) => JSON.stringify(readFileSync(join(ui, f), "utf8"));
writeFileSync(
  join(ui, "../src/ui.ts"),
  `// GENERATED by tools/gen-ui.mjs from packages/core/ui/ — edit those files, then \`npm run gen:ui\`.\n\n` +
    `export const UI_HTML: string = ${read("index.html")};\n\nexport const WEB_MANIFEST: string = ${read("manifest.webmanifest")};\n\nexport const ICON_SVG: string = ${read("icon.svg")};\n`,
);
