#!/usr/bin/env node
// ash's own apps (packages/apps/<id>) bundled into one module the core carries: app.json, a single-file server, the icon.
// The core puts each into <container>/root/apps/<id>/ when it is missing or older. Edit the app, then `npm run gen:apps`.
// Also the app contract (docs/APP-CONTRACT.md) and its example app (docs/examples/hello), which the core serves to agents
// (apps.contract) and copies next to the apps.
import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const appsDir = join(root, "packages/apps");
const out = [];
for (const id of readdirSync(appsDir).sort()) {
  const dir = join(appsDir, id);
  if (!existsSync(join(dir, "app.json"))) continue;
  const manifest = JSON.parse(readFileSync(join(dir, "app.json"), "utf8"));
  const bundled = await build({ entryPoints: [join(dir, "src/server.mjs")], bundle: true, write: false, platform: "node", format: "esm", target: "node20",
    minify: true, legalComments: "none", loader: { ".html": "text" }, logLevel: "silent",
    banner: { js: "import{createRequire as __cr}from'node:module';const require=__cr(import.meta.url);" } });
  const files = { "app.json": `${JSON.stringify(manifest, null, 2)}\n`, "server.mjs": bundled.outputFiles[0].text };
  if (manifest.icon) files[manifest.icon] = readFileSync(join(dir, manifest.icon), "utf8");
  out.push({ id, version: manifest.version, files });
}
writeFileSync(join(root, "packages/core/src/apps/builtin.generated.ts"),
  `// GENERATED by tools/gen-apps.mjs from packages/apps/ — edit those files, then \`npm run gen:apps\`.\n\n` +
  `export const BUILTIN_APPS: { id: string; version: string; files: Record<string, string> }[] = ${JSON.stringify(out)};\n`);

const example = join(root, "docs/examples/hello");
const text = {}, binary = {};
const walk = (dir) => {
  for (const name of readdirSync(dir).sort()) {
    const file = join(dir, name);
    if (statSync(file).isDirectory()) { walk(file); continue; }
    const key = relative(example, file).split("\\").join("/");
    if (/\.(png|webp)$/.test(name)) binary[key] = readFileSync(file).toString("base64"); else text[key] = readFileSync(file, "utf8");
  }
};
walk(example);
writeFileSync(join(root, "packages/core/src/apps/contract.generated.ts"),
  `// GENERATED by tools/gen-apps.mjs from docs/APP-CONTRACT.md and docs/examples/hello — edit those, then \`npm run gen:apps\`.\n\n` +
  `export const APP_CONTRACT_DOC: string = ${JSON.stringify(readFileSync(join(root, "docs/APP-CONTRACT.md"), "utf8"))};\n` +
  `export const HELLO_EXAMPLE: Record<string, string> = ${JSON.stringify(text)};\n` +
  `export const HELLO_EXAMPLE_BINARY: Record<string, string> = ${JSON.stringify(binary)};\n`);
