#!/usr/bin/env node
// Keep the starting text of the pulse guidance and the heartbeat checklist, which the core seeds into the owner's home,
// byte-for-byte aligned with the templates shipped in packages/ash-skills/persona.
import { readFileSync, writeFileSync as writeFile, renameSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const writeFileSync = (path, text) => { const temp = `${path}.${process.pid}.tmp`; writeFile(temp, text); renameSync(temp, path); };
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const template = (name) => {
  const text = readFileSync(join(root, "packages/ash-skills/persona", name), "utf8");
  if (!text.trim()) throw new Error(`empty template: ${name}`);
  return text;
};
writeFileSync(join(root, "packages/core/src/prompts/persona.generated.ts"),
  `// GENERATED by tools/gen-persona.mjs from packages/ash-skills/persona/*.template.md.\n` +
  `export const PULSE_TEMPLATE: string = ${JSON.stringify(template("PULSE.template.md"))};\n` +
  `export const HEARTBEAT_TEMPLATE: string = ${JSON.stringify(template("HEARTBEAT.template.md"))};\n`);
